name: Deploy to Pages

on:
  # 手动触发
  workflow_dispatch:
  # 或者推送到 main 分支时触发
  push:
    branches: ["main"]

# ⭐ 关键：取消其他正在运行的
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # 如果是静态文件，直接部署
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # 改成你的构建目录
